version: 3
services:
  postgresql:
    container_name: openmetadata_postgresql
    image: docker.getcollate.io/openmetadata/postgresql:1.11.4
    restart: unless-stopped
    command: "--work_mem=10MB --max_connections=300"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
     - ./docker-volume/db-data-postgres:/var/lib/postgresql/data
     - ./docker/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - vda
    healthcheck:
      test: psql -U postgres -tAc 'select 1' -d openmetadata_db
      interval: 15s
      timeout: 10s
      retries: 10
networks:
  vda
